// Reused from SecureFlow — Patron reads these from the same contract

export interface Milestone {
  description: string;
  amount: string;
  status: "pending" | "submitted" | "approved" | "rejected" | "disputed" | "resolved";
  submittedAt?: number;
  approvedAt?: number;
  rejectionReason?: string;
}

export interface Escrow {
  id: string;
  payer: string;          // agent wallet address
  beneficiary: string;    // hired freelancer
  token: string;
  totalAmount: string;
  releasedAmount: string;
  status: "pending" | "active" | "completed" | "disputed" | "cancelled" | "refunded" | "expired";
  createdAt: number;
  duration: number;
  deadlineAt?: number;
  milestones: Milestone[];
  projectTitle?: string;
  projectDescription?: string;
  isOpenJob?: boolean;
  applications?: Application[];
  applicationCount?: number;
}

export interface Application {
  freelancerAddress: string;
  coverLetter: string;
  proposedTimeline: number;
  appliedAt: number;
  status: "pending" | "accepted" | "rejected";
}

// Patron-specific types

export interface PatronTask {
  id: string;
  instruction: string;           // raw human input: "I need a logo, $80, 3 days"
  brief: AcceptanceBrief;        // generated by Claude
  escrowId?: string;             // set after job is posted on-chain
  status: "briefing" | "posted" | "reviewing" | "active" | "reviewing_work" | "completed" | "failed";
  createdAt: number;
}

export interface AcceptanceBrief {
  title: string;
  budget: number;                // in USDC
  durationDays: number;
  criteria: string[];            // explicit acceptance checklist (5-8 items)
  deliverableFormat: string;     // e.g. "SVG + PNG, min 1000x1000px"
  revisionRounds: number;        // max revisions before human escalation
  briefHash?: string;            // keccak256 of criteria JSON, posted on-chain
}

export interface AgentDecision {
  id: string;
  taskId: string;
  type: "brief_generated" | "application_scored" | "applicant_accepted" | "work_approved" | "work_rejected" | "escalated";
  reasoning: string;             // Claude's written explanation
  target?: string;               // freelancer address if applicable
  score?: number;                // 0-100 for application scoring
  timestamp: number;
}

export interface NanopaymentRecord {
  txHash: string;
  amount: string;               // in USDC (micro amount)
  reason: string;               // "application_review_fee" | "decision_processing"
  timestamp: number;
}
